development:
  dialect: sqlite3
  datasource: relay.sqlite
  table: migrations
  dir: db/migrations

production:
  dialect: sqlite3
  datasource: relay.sqlite
  table: migrations
  dir: db/migrations
